//PLANNER ACTIONS
export const FETCH_UTS_TIMETABLE = 'FETCH_UTS_TIMETABLE';
export const FETCH_UTS_TIMETABLE_ERROR = 'FETCH_UTS_TIMETABLE';
export const SAVE_LOCAL_TIMETABLE_OK = 'SAVE_UTS_TIMETABLE_OK';
export const GET_LOCAL_TIMETABLE_OK = 'GET_UTS_TIMETABLE_OK';
export const GET_LOCAL_TIMETABLE_FAIL = 'GET_LOCAL_TIMETABLE_FAIL';
